project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - onglet/test.qmd 


website:
  back-to-top-navigation: true
  title: "Bike MAP"
  navbar:
    title: "Bike MAP"
    left:
      - text: "Accueil"
        href: index.html
      - text: "Onglet"
        href: onglet/test.qmd  


sidebar:
  - id: onglet
    title: "Onglet"
    collapse-level: 3
    contents:
      - onglet/test.qmd  


format:
  html:
    theme: solar


# project:
#   type: website
#   output-dir: docs
#   render :
#     - index.qmd
#     - docs/onglet/test.qmd

# website:
#   back-to-top-navigation: true
#   title: "Bike MAP"

# sidebar:
#   - id: onglet
#     title: "onglet"
#     collapse-level: 3
#     contents:
#       - docs/onglet/test.qmd



# format:
#   html:
#     theme: solar # ON PEUT CHANGER LE THEME PAS DE SOUCIS



