project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - webpage/prevision/prevision.qmd
    - webpage/video/video.qmd

resources:
  - map/ecoCompteurRoutes.html
  - map/ecoCompteurCercle.html
  - map/monday_map.html
  - map/tuesday_map.html
  - map/wednesday_map.html
  - map/thursday_map.html
  - map/friday_map.html
  - map/saturday_map.html
  - map/sunday_map.html
  - documentation/build/html/_static/**  



website:
  back-to-top-navigation: true
  title: "BikeMap"
  navbar:
    title: "BikeMap"
    left:
      - text: "Prévision"
        href: webpage/prevision/prevision.qmd 
      - text: "Vidéo"
        href: webpage/video/video.qmd 


sidebar:
  - id: onglet
    title: "Prévision"
    collapse-level: 3
    contents:
      - webpage/prevision/prevision.qmd

  - id: onglet
    title: "Vidéo"
    collapse-level: 3
    contents:
      - webpage/video/video.qmd      



format:
  html:
    format : solar
    css: style.css

scripts:
  - !expr cp -r build/html/* docs/