---
title: "BikeMap"
format: html
execute:
  enabled: true
---


Bienvenue sur le projet BikeMap !

Notre objectif est de vous informer sur le trafic cycliste à Montpellier afin de vous aider à choisir les meilleurs itinéraires et les moments les plus calmes pour vos trajets. Sur cette page, vous trouverez une carte sur laquelle pouvez explorer les zones de la ville avec une visualisation dynamique de l'intensité du trafic à vélo, vous aidant à choisir les itinéraires les plus adaptés à vos besoins. Que vous soyez un cycliste quotidien ou un utilisateur occasionnel, notre plateforme vous permet de mieux comprendre la circulation et de faciliter vos déplacements dans Montpellier.

- L'onglet *Prédiction* vous indique le trafic moyen de chaque jour le semaine.
- L'onglet *Vidéo* illustre la circulation sur la journée du .. .
- Le lien suivant vous donne accés à la documentation du projet : [documentation Sphinx ici](webpage/docu/index.html).
  
Cette carte interactive affiche le trafic cycliste de la veille. Les données se mettent à jour quotidiennement, vous permettant ainsi de planifier vos trajets en toute sérénité.

<iframe src="map/ecoCompteurRoutes.html" width="800" height="600"></iframe>

Cette carte vous donne l'intensité des éco-compteurs de Montpellier.

<iframe src="map/ecoCompteurCercle.html" width="800" height="600"></iframe>


