name: Déploiement de la documentation

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Sphinx and theme
        run: |
          pip install sphinx
          pip install sphinx_rtd_theme
          

      - name: Build documentation
        run: |
          cd documentation 
          make html  

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: documentation/build