name: Exécuter plusieurs scripts Python

on:

  schedule:
    - cron: "*/10 * * * *" # midi


  workflow_dispatch:

jobs:
  run_scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v3

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.5"  

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Exécuter Telechargement.py
        run: |
          python code/DataProcessing/Telechargement.py


      - name: Exécuter mapecocercle
        run: |
          python code/MapCrea/EcoCompteurMap.py

      - name: Exécuter CirculationDuJour.py
        run: |
          python code/MapCrea/CirculationDuJour.py
  

      # - name: Exécuter MapPREDiction
      #   run: |
      #     python code/predictive_map.py

      - name: Installer Quarto
        uses: quarto-dev/quarto-actions/setup@v2


      - name: Installer nbformat et Jupyter
        run: |
          python -m pip install nbformat jupyter
  
      - name: Rendre le site Quarto
        run: |
          quarto render
  
      - name: Déployer le site (GitHub Pages)
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Mise à jour automatique du site"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  