name: Exécuter code/Telechargement.py

on:
  # Planifier l'exécution tous les jours à 11h UTC
  schedule:
    - cron: "*/15 * * * *"

  # Permet de lancer manuellement le workflow
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v3

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.5"

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Exécuter le script Python
        run: |
          python code/Telechargement.py
